# Site settings
title: Ashish Chaudhary
description: "Ashish Chaudhary's blog"
url: "https://ashishchaudhary.in"
author:
  name: "Ashish Chaudhary"
  email: "me@ashishchaudhary.in"
  url: "https://ashishchaudhary.in"

# Build settings
baseurl: /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
copyright : ""
owner : "Ashish Chaudhary"
year : "© 2017"

future: true

# Options
custom_header: false
custom_nav_footer: false
reverse: false

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
